name: Cypress Tests

on:
  workflow_dispatch:        # permite rodar manualmente
  schedule:
    - cron: "0 11 * * 1"    # toda segunda às 08h (BR)

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Rodar Cypress
        uses: cypress-io/github-action@v6
        with:
          record: true            # grava no Cypress Cloud
          browser: chrome         # opcional, mas recomendado
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
