name: Cypress Tests

on:
  workflow_dispatch:        # permite rodar manualmente
  schedule:
    - cron: "0 14 * * 1"    # seg às 11h no Brasil (-3) => 14h UTC

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Rodar Cypress
        uses: cypress-io/github-action@v6
        with:
          record: true
          browser: chrome
          # se você tiver build, use:
          # build: npm run build
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
